name: Release

on:
  push:
    branches: [ main ]

jobs:
  publish:
    uses: Spryx-AI/spryx-devops-workflows/.github/workflows/spryx-pypi-publish.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      python-version: "3.12"         # Optional, Python version to use (default: "3.12")
      publish-to-testpypi: false     # Optional, also publish to TestPyPI (default: false)
      check-description: true        # Optional, validate package description (default: true)
    secrets: inherit